
unitecms_storage_sign:
    resource: "@UniteCMSStorageBundle/Controller/SignController.php"
    type:     annotation
    prefix:   /{domain}/api/storage/sign
    host:     '{organization}.{hostname}'
    requirements:
        domain: '%identifier_url_pattern%'
        organization: '%identifier_url_pattern%'
        hostname: '%allowed_hostname%'
    defaults:
        hostname: '%default_hostname%'
