services:
    # A file upload field.
    UnitedCMS\StorageBundle\Field\Types\FileFieldType:
        tags: [united_cms.field_type]
        arguments: ['@router.default', '%kernel.secret%']

    UnitedCMS\StorageBundle\SchemaType\StorageFileType:
        tags: [united_cms.graphql.schema_type]

    UnitedCMS\StorageBundle\SchemaType\StorageFileInputType:
        tags: [united_cms.graphql.schema_type]


    UnitedCMS\StorageBundle\Command\StorageFileDeleteUnused:
        arguments: ['@doctrine.orm.default_entity_manager']
        tags:
            - { name: 'console.command', command: 'united:storage:delete-unused' }